name = "2071-mektup"
main = "worker.js"
compatibility_date = "2026-08-22"

[[d1_databases]]
binding = "DB"
database_name = "2071-mektup"
database_id = "2fb79ec1-6f1c-45a4-933c-7c155d045f83"
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "2071-mektup-media"
